changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo-mesh/issues/1584
    description: >
      Add a `meshctl cluster configure` command that interactively allows the user to generate a file
      that is referenced in subsequent meshctl commands which automate cluster interaction.
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo-mesh/issues/1584
    description: >
      Add a `meshctl cluster list` command that allows the user to list all
      the registered clusters.