### CA RBAC ###
kind: {{if not .SingleNamespace}}Cluster{{end}}Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-{{.Namespace}}-ca
  {{- if .SingleNamespace}}
      namespace: {{.Namespace}}
      {{- end}}
          rules:
              - apiGroups: [""]
          resources: ["configmaps"]
            verbs: ["create"]
            - apiGroups: [""]
              resources: ["configmaps"]
              resourceNames: [{{.TLSTrustAnchorConfigMapName}}]
              verbs: ["update"]
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["list", "get", "watch"]
            - apiGroups: ["extensions", "apps"]
              resources: ["replicasets"]
              verbs: ["list", "get", "watch"]
            - apiGroups: [""]
              resources: ["secrets"]
              verbs: ["create", "update"]
          {{- if and .EnableTLS .ProxyAutoInjectEnabled }}
              - apiGroups: ["admissionregistration.k8s.io"]
                resources: ["mutatingwebhookconfigurations"]
                verbs: ["list", "get", "watch"]
              {{- end }}

