### Controller RBAC ###

kind: {{if not .SingleNamespace}}Cluster{{end}}Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-{{.Namespace}}-controller
  {{- if .SingleNamespace}}
      namespace: {{.Namespace}}
      {{- end}}
          rules:
              - apiGroups: ["extensions", "apps"]
          resources: ["deployments", "replicasets"]
            verbs: ["list", "get", "watch"]
            - apiGroups: [""]
              resources: ["pods", "endpoints", "services", "namespaces", "replicationcontrollers"]
              verbs: ["list", "get", "watch"]
            - apiGroups: ["linkerd.io"]
              resources: ["serviceprofiles"]
              verbs: ["list", "get", "watch"]
