### Controller RBAC ###

kind: {{if not .SingleNamespace}}Cluster{{end}}RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-{{.Namespace}}-controller
  {{- if .SingleNamespace}}
      namespace: {{.Namespace}}
      {{- end}}
          roleRef:
              apiGroup: rbac.authorization.k8s.io
                kind: {{if not .SingleNamespace}}Cluster{{end}}Role
                name: linkerd-{{.Namespace}}-controller
                subjects:
                - kind: ServiceAccount
                name: linkerd-controller
                namespace: {{.Namespace}}
