apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.0.0
  labels:
    linkerd.io/control-plane-component: controller
  name: proxy-api
  namespace: linkerd
spec:
  ports:
  - name: grpc
    port: 8086
    targetPort: 8086
  selector:
    linkerd.io/control-plane-component: controller
  type: ClusterIP
