
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "1.3.0"
  name = "github.com/gogo/protobuf"

[[override]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/go-checkpoint"
  version = "0.0.4"

[[constraint]]
  name = "github.com/solo-io/build"
  version = "0.0.4"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.9.12"

[[override]]
  name = "github.com/solo-io/go-utils"
  version = "0.10.7"

[[constraint]]
  name = "github.com/solo-io/gloo"
  version = "0.14.1"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.8.0"

# this override is required to make prometheus work
[[override]]
  name = "k8s.io/client-go"
  version = "10.0.0"

# this override is required to make prometheus work
[[override]]
  name = "k8s.io/kubernetes"
  version = "1.13.0"

# this override is required to make prometheus work
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.0"

# this override is required to make prometheus work
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.0"

# this override is required to make prometheus work
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "23.2.0"

# this override is required to make prometheus work
[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

[[constraint]]
  name = "github.com/linkerd/linkerd2"
  version = "stable-2.3.0"

[[override]]
 name = "go.opencensus.io"
 version = "0.22.0"

[[override]]
 name = "github.com/Masterminds/sprig"
 version = "2.17.0"