kind: ServiceAccount
apiVersion: v1
metadata:
  name: mesh-discovery
  namespace: mesh-discovery

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-discovery
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "secrets", "endpoints", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create"]
  - apiGroups: ["supergloo.solo.io"]
    resources: ["*"]
    verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mesh-discovery-role-binding
subjects:
  - kind: ServiceAccount
    name: mesh-discovery
    namespace: mesh-discovery
roleRef:
  kind: ClusterRole
  name: mesh-discovery
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mesh-discovery
  namespace: mesh-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      supergloo: supergloo
  template:
    metadata:
      labels:
        supergloo: supergloo
        app: supergloo
    spec:
      serviceAccountName: mesh-discovery
      containers:
        - image: "quay.io/solo-io/mesh-discovery:0.3.12"
          imagePullPolicy:  Never
          name: mesh-discovery
          args: ["--disable-config"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace