changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo-mesh/issues/996
    description: Introduce new Settings CRD for global settings configuration.
    resolvesIssue: false
