changelog:
  - type: NEW_FEATURE
    issueLink: https://github.com/solo-io/gloo-mesh/issues/1086
    description: Add a toggle to Settings to enable detection and error reporting when networking translates VirtualServices or Destination rules that intersect with externally provided VirtualServices/DestinationRules.
  - type: FIX
    issueLink: https://github.com/solo-io/gloo-mesh/issues/1096
    description: Fix DestinationRules not being output even if they contain outlier detection config.
