# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/go/src/github.com/solo-io/service-mesh-hub
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install go
          command: |
          sudo rm -rf /usr/local/go && \
          wget https://golang.org/dl/go1.14.6.linux-amd64.tar.gz && \
          tar -xvf go1.14.6.linux-amd64.tar.gz && sudo mv go /usr/local/go && \
          export GOROOT=/usr/local/go && \
          export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      - run:
          name: install deps
          command: |
            make install-go-tools
      - run:
          name: unit tests
          command: |
            make run-tests SKIP_PACKAGES=test/e2e
