apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mesh-discovery-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.zephyr.solo.io"]
    resources: ["meshes", "meshworkloads", "meshservices", "kubernetesclusters"]
    verbs: ["*"]
