---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: supergloo
  namespace: {{ .Release.Namespace }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: discovery
  namespace: {{ .Release.Namespace }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: mesh-discovery
  namespace: {{ .Release.Namespace }}