{{- if .Values.rbac.create }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: supergloo
rules:
- apiGroups: ["supergloo.solo.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["gloo.solo.io"]
  resources: ["upstreams"]
  verbs: ["read", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
# istio crds
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules"]
  verbs: ["*"]
- apiGroups: ["policies.istio.io"]
  resources: ["virtualservices", "meshpolicies"]
  verbs: ["*"]
- apiGroups: ["rbac.istio.io"]
  resources: ["rbacconfigs", "serviceroles", "servicerolebindings"]
  verbs: ["*"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "secrets", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: ["gloo.solo.io"]
  resources: ["settings", "upstreams"]
  verbs: ["*"]

{{- end }}
