---
apiVersion: v1
kind: Namespace
metadata:
  name: supergloo-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-admin-supergloo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: supergloo-system
---
### Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: supergloo
  namespace: supergloo-system
  labels:
    gloo: supergloo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        gloo: supergloo
    spec:
      containers:
      - name: supergloo
        image: quay.io/solo-io/supergloo:dev
        imagePullPolicy: Always
---
### Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: supergloo
    gloo: discovery
  name: discovery
  namespace: supergloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      supergloo: discovery
  template:
    metadata:
      labels:
        supergloo: discovery
    spec:
      containers:
        - image: "soloio/discovery:0.6.14"
          imagePullPolicy: Always
          name: discovery
          args: ["--namespace=supergloo-system" ]
