changelog:
  - type: NEW_FEATURE
    description: Expose new Settings CRD that allows user configuration of SMH discovery for AWS resources.
    issueLink: https://github.com/solo-io/gloo-mesh/issues/685
