########################################################################
###                                                                  ###
###                        Supergloo                                 ###
###                                                                  ###
########################################################################

# This file is used by the generate-values.go script to create
# the standard values.yaml which is shipped with the SuperGloo chart.

rbac:
  create: true

supergloo:
  deployment:
    image:
      repository: quay.io/solo-io/supergloo
      pullPolicy: Always
    stats: true
  sidecarInjectorImage:
    repository: quay.io/solo-io/sidecar-injector
    pullPolicy: IfNotPresent

discovery:
  deployment:
    image:
      repository: quay.io/solo-io/discovery
      pullPolicy: Always
    stats: true
    disablePrometheusBouncer: false

meshDiscovery:
  deployment:
    image:
      repository: quay.io/solo-io/mesh-discovery
      pullPolicy: Always
    stats: true
