changelog:
  - type: FIX
    issueLink: https://github.com/solo-io/gloo-mesh/issues/1238
    description: Respect `KUBECONFIG` env var if kubeconfig is not explicitly specified through `--kubeconfig`.
