name: Docs

on:
  push:
    branches:
    - 'master'
  release:
    types:
    - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Install Protoc
      uses: arduino/setup-protoc@v1.1.0
      with:
        version: '3.6.1'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update deps
      run: make update-deps

    - name: Update versioned docs site
      run: ./ci/build-docs-site.sh
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
