name: e2e_test

on:
  pull_request:
    branches:
      - 'master'

jobs:
  e2e:
    name: e2e-appmesh-eks
    runs-on: ubuntu-18.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test
        if: contains( github.event.pull_request.labels.*.name, 'e2e-appmesh-eks')
        run: |
          echo "Hello World!"
