name: Docs

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    name: Generate versioned docs site
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Install Protoc
      uses: solo-io/setup-protoc@master
      with:
        version: '3.6.1'
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update deps
      run: |
        make install-go-tools

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GC_GHA_SA_JSON_KEY }}

    - name: Generate versioned docs site
      env:
        RELEASE: true
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: make -C docs build-site
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        PROJECT_ID: solo-corp
        PROJECT_PATH: ./docs/ci
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
