name: Release

on:
  # TODO remove after testing
  pull_request: {}
  release:
    types:
      - prereleased

jobs:
  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        ref: refs/tags/v0.7.0

      - name: Set Release Tag
        run: echo ::set-env name=TAGGED_VERSION::${GITHUB_REF#refs/*/}

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make upload-github-release-assets

      - name: Push Docker Images
        run: |
          echo ${{ secrets.CI_ADMIN_DOCKER_HUB_PASSWORD }} | docker login -u soloiobot --password-stdin
          make push-all-images

      - name: Publish Helm Charts
        run: |
          make publish-chart
